baseurl = "https://katharineme.com/"
title = "Katharine Medetgul-Ernar"
publishDir = "docs/"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Katharine Medetgul-Ernar"
    description = "Genomics and Computer Science"
    keywords = "blog,developer,personal"
    info = "Genomics and Computer Science Blog"
    avatarurl = "images/profile.jpg"
    footercontent = "Enter a text here."

    hideCredits = false
    hideCopyright = false

    thumbnail = "images/cells.jpg"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/KatharineME/"


[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "The Art of Genome Analysis"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Katharine Medetgul-Ernar"
            info = "Computational Genomics Blog"
            description = "Computational Genomics Blog"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "Posts"
                weight = 2.0
                url = "posts"
